version: 2

project_name: agrep

builds:
  - id: agrep
    main: ./cmd/agrep
    binary: agrep
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - dragonfly
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: dragonfly
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - ids:
      - agrep
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: github
  sort: asc

release:
  draft: false
  prerelease: auto

